In [1]:
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
from selenium import webdriver
import time
import pandas as pd

In [2]:
def get_job_data(keyword, num_jobs, verbose, path, slp_time):
    
    '''Gathers jobs as a dataframe, scraped from Glassdoor'''
    
    #Initializing the webdriver
    options = webdriver.ChromeOptions()
    
    #Uncomment the line below if you'd like to scrape without a new Chrome window every time.
    #options.add_argument('headless')
    
    #Change the path to where chromedriver is in your home folder.
    driver = webdriver.Chrome(executable_path=path, options=options)
    driver.set_window_size(1120, 1000)
    
    url = "https://www.glassdoor.com/Job/jobs.htm?suggestCount=0&suggestChosen=false&clickSource=searchBtn&typedKeyword="+keyword+"&sc.keyword="+keyword+"&locT=&locId=&jobType="
    #url = 'https://www.glassdoor.com/Job/jobs.htm?sc.keyword="' + keyword + '"&locT=C&locId=1147401&locKeyword=San%20Francisco,%20CA&jobType=all&fromAge=-1&minSalary=0&includeNoSalaryJobs=true&radius=100&cityId=-1&minRating=0.0&industryId=-1&sgocId=-1&seniorityType=all&companyId=-1&employerSizes=0&applicationType=0&remoteWorkType=0'
    driver.get(url)
    jobs = []

    while len(jobs) < num_jobs:  #If true, should be still looking for new jobs.

        #Let the page load. Change this number based on your internet speed.
        #Or, wait until the webpage is loaded, instead of hardcoding it.
        time.sleep(slp_time)

        #Test for the "Sign Up" prompt and get rid of it.
        try:
            driver.find_element_by_class_name("selected").click()
        except ElementClickInterceptedException:
            pass

        time.sleep(.1)

        try:
            driver.find_element_by_css_selector('[alt="Close"]').click() #clicking to the X.
            print(' x out worked')
        except NoSuchElementException:
            print(' x out failed')
            pass

        
        #Going through each job in this page
        job_buttons = driver.find_elements_by_class_name("jl")  #jl for Job Listing. These are the buttons we're going to click.
        for job_button in job_buttons:  

            print("Progress: {}".format("" + str(len(jobs)) + "/" + str(num_jobs)))
            if len(jobs) >= num_jobs:
                break

            job_button.click()  #You might 
            time.sleep(1)
            collected_successfully = False
            
            while not collected_successfully:
                try:
                    company_name = driver.find_element_by_xpath('.//div[@class="employerName"]').text
                    location = driver.find_element_by_xpath('.//div[@class="location"]').text
                    job_title = driver.find_element_by_xpath('.//div[contains(@class, "title")]').text
                    job_description = driver.find_element_by_xpath('.//div[@class="jobDescriptionContent desc"]').text
                    collected_successfully = True
                except:
                    time.sleep(5)

            try:
                salary_estimate = driver.find_element_by_xpath('.//span[@class="gray salary"]').text
            except NoSuchElementException:
                salary_estimate = -1 #You need to set a "not found value. It's important."
            
            try:
                rating = driver.find_element_by_xpath('.//span[@class="rating"]').text
            except NoSuchElementException:
                rating = -1 #You need to set a "not found value. It's important."

            #Printing for debugging
            if verbose:
                print("Job Title: {}".format(job_title))
                print("Salary Estimate: {}".format(salary_estimate))
                print("Job Description: {}".format(job_description[:500]))
                print("Rating: {}".format(rating))
                print("Company Name: {}".format(company_name))
                print("Location: {}".format(location))

            #Going to the Company tab...
            #clicking on this:
            #<div class="tab" data-tab-type="overview"><span>Company</span></div>
            try:
                driver.find_element_by_xpath('.//div[@class="tab" and @data-tab-type="overview"]').click()

                try:
                    #<div class="infoEntity">
                    #    <label>Headquarters</label>
                    #    <span class="value">San Francisco, CA</span>
                    #</div>
                    headquarters = driver.find_element_by_xpath('.//div[@class="infoEntity"]//label[text()="Headquarters"]//following-sibling::*').text
                except NoSuchElementException:
                    headquarters = -1

                try:
                    size = driver.find_element_by_xpath('.//div[@class="infoEntity"]//label[text()="Size"]//following-sibling::*').text
                except NoSuchElementException:
                    size = -1

                try:
                    founded = driver.find_element_by_xpath('.//div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*').text
                except NoSuchElementException:
                    founded = -1

                try:
                    type_of_ownership = driver.find_element_by_xpath('.//div[@class="infoEntity"]//label[text()="Type"]//following-sibling::*').text
                except NoSuchElementException:
                    type_of_ownership = -1

                try:
                    industry = driver.find_element_by_xpath('.//div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*').text
                except NoSuchElementException:
                    industry = -1

                try:
                    sector = driver.find_element_by_xpath('.//div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*').text
                except NoSuchElementException:
                    sector = -1

                try:
                    revenue = driver.find_element_by_xpath('.//div[@class="infoEntity"]//label[text()="Revenue"]//following-sibling::*').text
                except NoSuchElementException:
                    revenue = -1

                try:
                    competitors = driver.find_element_by_xpath('.//div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*').text
                except NoSuchElementException:
                    competitors = -1

            except NoSuchElementException:  #Rarely, some job postings do not have the "Company" tab.
                headquarters = -1
                size = -1
                founded = -1
                type_of_ownership = -1
                industry = -1
                sector = -1
                revenue = -1
                competitors = -1

                
            if verbose:
                print("Headquarters: {}".format(headquarters))
                print("Size: {}".format(size))
                print("Founded: {}".format(founded))
                print("Type of Ownership: {}".format(type_of_ownership))
                print("Industry: {}".format(industry))
                print("Sector: {}".format(sector))
                print("Revenue: {}".format(revenue))
                print("Competitors: {}".format(competitors))
                print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")

            jobs.append({"Job Title" : job_title,
            "Salary Estimate" : salary_estimate,
            "Job Description" : job_description,
            "Rating" : rating,
            "Company Name" : company_name,
            "Location" : location,
            "Headquarters" : headquarters,
            "Size" : size,
            "Founded" : founded,
            "Type of ownership" : type_of_ownership,
            "Industry" : industry,
            "Sector" : sector,
            "Revenue" : revenue,
            "Competitors" : competitors})
            #add job to jobs
            
            
        #Clicking on the "next page" button
        try:
            driver.find_element_by_xpath('.//li[@class="next"]//a').click()
        except NoSuchElementException:
            print("Scraping terminated before reaching target number of jobs. Needed {}, got {}.".format(num_jobs, len(jobs)))
            break

    return pd.DataFrame(jobs)  #This line converts the dictionary object into a pandas DataFrame.

In [3]:
path = './chromedriver'
df = get_job_data("data scientist", 15, False, path,15)

 x out worked
Progress: 0/15
Progress: 1/15
Progress: 2/15
Progress: 3/15
Progress: 4/15
Progress: 5/15
Progress: 6/15
Progress: 7/15
Progress: 8/15
Progress: 9/15
Progress: 10/15
Progress: 11/15
Progress: 12/15
Progress: 13/15
Progress: 14/15
Progress: 15/15

In [4]:
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Senior Data Engineer (m/f/x),-1,Senior Data Engineer (m/f/x)\nData & BI\nDeuts...,3.8,Visable GmbH\n3.8,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
1,Data Scientist,-1,"Data Scientist\n\nBerlin, asap\n\nHeadquartere...",3.3,Mapp Digital\n3.3,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
2,Head of Engineering - Data Platform,-1,Zalando is a highly digitized business which p...,3.6,Zalando SE\n3.6,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
3,AI Data Scientist / Signal Processing (f/m/d),-1,WHO WE ARE?\n\nThe WOW Tech Group is one of th...,4.2,WOW Tech Group\n4.2,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
4,Data Scientist/ Senior Clinical Data Manager (...,-1,"Für unseren Kunden, ein weltweit führendes Pha...",3.4,Kelly Services GmbH\n3.4,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
5,Data Engineer (m/f/x),-1,Description\n\nHashtag You is part of an ambit...,-1,AVA & MAY,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
6,Data Scientist (m/w/d) Projektmanagement/Machi...,-1,Was Sie erwartet?\n\nSie ermitteln und extrahi...,4.8,Campusjäger GmbH\n4.8,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
7,Senior Backend/Data Engineer- Data Governance,-1,As a Backend/Data Engineer in the Data Managem...,3.6,Zalando SE\n3.6,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
8,Data Scientist/ Senior Clinical Data Manager (...,-1,"Für unseren Kunden, ein weltweit führendes Pha...",3.4,Kelly Services GmbH\n3.4,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
9,Data Engineer (m/f/d),-1,We’re a mighty team of more than 300 creative ...,4.5,Uberall\n4.5,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
10,Data Scientist (f/m/x),-1,"BERLIN, HAMBURG, LISBON, STUTTGART\nAre you lo...",3.6,diconium group\n3.6,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
11,Data Scientist (m/w/d),-1,"(Berlin, Vollzeit, unbefristet, ab sofort)\n\n...",4.2,Sony Music Entertainment Germany\n4.2,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
12,Data Scientist (m/w/d),-1,"Vollzeit, unbefristet\nBerlin, Köln\n\nKienbau...",3.6,Kienbaum\n3.6,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
13,Data Scientist (f/m/d),-1,Your Mission\nAs a member of our team you will...,-1,Hypatos GmbH,Berlim,-1,-1,-1,-1,-1,-1,-1,-1
14,Data Scientist (m/w/d),-1,Data Scientist (m/w/d) im Autismus-Spektrum\n\...,5.0,auticon GmbH\n5.0,Berlim,-1,-1,-1,-1,-1,-1,-1,-1